package com.cyan.entity;

public class Cart {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.cart_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer cartId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cart.cart_sum
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Double cartSum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.cart_id
	 * @return  the value of cart.cart_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getCartId() {
		return cartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.cart_id
	 * @param cartId  the value for cart.cart_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.user_id
	 * @return  the value of cart.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.user_id
	 * @param userId  the value for cart.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cart.cart_sum
	 * @return  the value of cart.cart_sum
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Double getCartSum() {
		return cartSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cart.cart_sum
	 * @param cartSum  the value for cart.cart_sum
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setCartSum(Double cartSum) {
		this.cartSum = cartSum;
	}
}