package com.cyan.entity;

public class Creditcard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditcard.card_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    private Integer cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditcard.user_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditcard.card_number
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    private Long cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditcard.holder_name
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    private String holderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditcard.cvv
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    private Integer cvv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditcard.expire_year
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    private Integer expireYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditcard.expire_month
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    private Integer expireMonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditcard.card_id
     *
     * @return the value of creditcard.card_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Integer getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditcard.card_id
     *
     * @param cardId the value for creditcard.card_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditcard.user_id
     *
     * @return the value of creditcard.user_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditcard.user_id
     *
     * @param userId the value for creditcard.user_id
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditcard.card_number
     *
     * @return the value of creditcard.card_number
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Long getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditcard.card_number
     *
     * @param cardNumber the value for creditcard.card_number
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setCardNumber(Long cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditcard.holder_name
     *
     * @return the value of creditcard.holder_name
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public String getHolderName() {
        return holderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditcard.holder_name
     *
     * @param holderName the value for creditcard.holder_name
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setHolderName(String holderName) {
        this.holderName = holderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditcard.cvv
     *
     * @return the value of creditcard.cvv
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Integer getCvv() {
        return cvv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditcard.cvv
     *
     * @param cvv the value for creditcard.cvv
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setCvv(Integer cvv) {
        this.cvv = cvv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditcard.expire_year
     *
     * @return the value of creditcard.expire_year
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Integer getExpireYear() {
        return expireYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditcard.expire_year
     *
     * @param expireYear the value for creditcard.expire_year
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setExpireYear(Integer expireYear) {
        this.expireYear = expireYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditcard.expire_month
     *
     * @return the value of creditcard.expire_month
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public Integer getExpireMonth() {
        return expireMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditcard.expire_month
     *
     * @param expireMonth the value for creditcard.expire_month
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    public void setExpireMonth(Integer expireMonth) {
        this.expireMonth = expireMonth;
    }
}