package com.cyan.entity;

public class Department {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.department_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.department_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private String departmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.description
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.department_id
	 * @return  the value of department.department_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.department_id
	 * @param departmentId  the value for department.department_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.department_name
	 * @return  the value of department.department_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.department_name
	 * @param departmentName  the value for department.department_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.description
	 * @return  the value of department.description
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.description
	 * @param description  the value for department.description
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}