package com.cyan.entity;

public class Orderdetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.detail_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer detailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.order_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.price
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.quantity
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orderdetail.total
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Double total;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.detail_id
	 * @return  the value of orderdetail.detail_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getDetailId() {
		return detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.detail_id
	 * @param detailId  the value for orderdetail.detail_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.order_id
	 * @return  the value of orderdetail.order_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.order_id
	 * @param orderId  the value for orderdetail.order_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.product_id
	 * @return  the value of orderdetail.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.product_id
	 * @param productId  the value for orderdetail.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.price
	 * @return  the value of orderdetail.price
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.price
	 * @param price  the value for orderdetail.price
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.quantity
	 * @return  the value of orderdetail.quantity
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.quantity
	 * @param quantity  the value for orderdetail.quantity
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orderdetail.total
	 * @return  the value of orderdetail.total
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Double getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orderdetail.total
	 * @param total  the value for orderdetail.total
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setTotal(Double total) {
		this.total = total;
	}
}