package com.cyan.entity;

import java.util.Date;

public class Payment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.payment_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer paymentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.card_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer cardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.order_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment.payment_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Date paymentDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.payment_id
	 * @return  the value of payment.payment_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getPaymentId() {
		return paymentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.payment_id
	 * @param paymentId  the value for payment.payment_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.card_id
	 * @return  the value of payment.card_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.card_id
	 * @param cardId  the value for payment.card_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.order_id
	 * @return  the value of payment.order_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.order_id
	 * @param orderId  the value for payment.order_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment.payment_date
	 * @return  the value of payment.payment_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Date getPaymentDate() {
		return paymentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment.payment_date
	 * @param paymentDate  the value for payment.payment_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}
}