package com.cyan.entity;

public class Picture {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.picture_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer pictureId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.picture_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private String pictureName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.path
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private String path;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.picture_id
	 * @return  the value of picture.picture_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getPictureId() {
		return pictureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.picture_id
	 * @param pictureId  the value for picture.picture_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.product_id
	 * @return  the value of picture.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.product_id
	 * @param productId  the value for picture.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.picture_name
	 * @return  the value of picture.picture_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getPictureName() {
		return pictureName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.picture_name
	 * @param pictureName  the value for picture.picture_name
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPictureName(String pictureName) {
		this.pictureName = pictureName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.path
	 * @return  the value of picture.path
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.path
	 * @param path  the value for picture.path
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setPath(String path) {
		this.path = path;
	}
}