package com.cyan.entity;

import java.util.Date;

public class Review {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column review.review_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer reviewId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column review.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column review.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column review.review_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Date reviewDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column review.star_ranking
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private Integer starRanking;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column review.review_content
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	private String reviewContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column review.review_id
	 * @return  the value of review.review_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getReviewId() {
		return reviewId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column review.review_id
	 * @param reviewId  the value for review.review_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column review.user_id
	 * @return  the value of review.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column review.user_id
	 * @param userId  the value for review.user_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column review.product_id
	 * @return  the value of review.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column review.product_id
	 * @param productId  the value for review.product_id
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column review.review_date
	 * @return  the value of review.review_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Date getReviewDate() {
		return reviewDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column review.review_date
	 * @param reviewDate  the value for review.review_date
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column review.star_ranking
	 * @return  the value of review.star_ranking
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public Integer getStarRanking() {
		return starRanking;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column review.star_ranking
	 * @param starRanking  the value for review.star_ranking
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setStarRanking(Integer starRanking) {
		this.starRanking = starRanking;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column review.review_content
	 * @return  the value of review.review_content
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public String getReviewContent() {
		return reviewContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column review.review_content
	 * @param reviewContent  the value for review.review_content
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	public void setReviewContent(String reviewContent) {
		this.reviewContent = reviewContent;
	}
}