package com.cyan.mapper;

import com.cyan.entity.Cart;
import com.cyan.entity.CartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	long countByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int deleteByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int deleteByPrimaryKey(Integer cartId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int insert(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int insertSelective(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	List<Cart> selectByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	Cart selectByPrimaryKey(Integer cartId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExampleSelective(@Param("record") Cart record, @Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExample(@Param("record") Cart record, @Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKeySelective(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKey(Cart record);
}