package com.cyan.mapper;

import com.cyan.entity.Category;
import com.cyan.entity.CategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	long countByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int deleteByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int deleteByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int insert(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int insertSelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	List<Category> selectByExampleWithBLOBs(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	List<Category> selectByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	Category selectByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") Category record, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKey(Category record);
}