package com.cyan.mapper;

import com.cyan.entity.Creditcard;
import com.cyan.entity.CreditcardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditcardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    long countByExample(CreditcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    int deleteByExample(CreditcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    int deleteByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    int insert(Creditcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    int insertSelective(Creditcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    List<Creditcard> selectByExample(CreditcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    Creditcard selectByPrimaryKey(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    int updateByExampleSelective(@Param("record") Creditcard record, @Param("example") CreditcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    int updateByExample(@Param("record") Creditcard record, @Param("example") CreditcardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    int updateByPrimaryKeySelective(Creditcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditcard
     *
     * @mbg.generated Mon Feb 26 10:47:49 EST 2018
     */
    int updateByPrimaryKey(Creditcard record);
}