package com.cyan.mapper;

import com.cyan.entity.Payment;
import com.cyan.entity.PaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	long countByExample(PaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int deleteByExample(PaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int deleteByPrimaryKey(Integer paymentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int insert(Payment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int insertSelective(Payment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	List<Payment> selectByExample(PaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	Payment selectByPrimaryKey(Integer paymentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExampleSelective(@Param("record") Payment record, @Param("example") PaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExample(@Param("record") Payment record, @Param("example") PaymentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKeySelective(Payment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table payment
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKey(Payment record);
}