package com.cyan.mapper;

import com.cyan.entity.Picture;
import com.cyan.entity.PictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PictureMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	long countByExample(PictureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int deleteByExample(PictureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int deleteByPrimaryKey(Integer pictureId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int insert(Picture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int insertSelective(Picture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	List<Picture> selectByExample(PictureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	Picture selectByPrimaryKey(Integer pictureId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExampleSelective(@Param("record") Picture record, @Param("example") PictureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByExample(@Param("record") Picture record, @Param("example") PictureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKeySelective(Picture record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table picture
	 * @mbg.generated  Mon Feb 26 10:47:49 EST 2018
	 */
	int updateByPrimaryKey(Picture record);
}